/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package l_m_s.interfaces;

import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import l_m_s.classes.Admin;
import l_m_s.classes.Student;
import l_m_s.classes.Teacher;

/**
 *
 * @author azizm
 */
public class teacherFrame extends javax.swing.JFrame {

    /**
     * Creates new form studentFrame
     */
    
    mainFrame mfr;
    DefaultTableModel tmodel;
    Teacher temp;
    public teacherFrame(mainFrame m,int tid) {
        initComponents();
        mfr=m;
        
        Admin a = Admin.getinstance();
        temp=a.getTeacher(tid);
        Label_Roll.setText("Teacher ID: "+Integer.toString(temp.gettId()) );
        Label_Fname.setText("Teacher First Name: "+temp.getfName());
        Label_LastName.setText("Teacher Last Name: "+temp.getlName());
        Label_Contact.setText("Teacher Contact: "+Integer.toString(temp.getContact()));
        Label_Gender.setText("Teacher Gender: "+temp.getGender());
        Label_Address.setText("Teacher Address: "+temp.getAddress());
        tmodel = (DefaultTableModel) jTable1.getModel();
        if(temp.getSec_teaching().isEmpty()){
            errorLabel.setText("!Currently Teaching NO Section!");
            jPanel1.setVisible(false);
        }
        else{
            jPanel1.setVisible(true);
            for (int i = 0; i < temp.getSec_teaching().size(); i++) {
                tmodel.insertRow(tmodel.getRowCount(),new Object[]{a.getCourseNameFromSectionID(temp.getSec_teaching().get(i)),temp.getSec_teaching().get(i)});
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showAttendance sat = new showAttendance(this, Integer.parseInt(this.secTF.getText()));
        sat.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.mfr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mainFrame mff = new mainFrame();
        mff.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showMarks marks = new showMarks(this,Integer.parseInt(this.secTF.getText()));
        marks.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showEvaluation show = new showEvaluation(this, Integer.parseInt(this.secTF.getText()));
        show.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_Contact;
    private javax.swing.JLabel Label_Fname;
    private javax.swing.JLabel Label_Gender;
    private javax.swing.JLabel Label_LastName;
    private javax.swing.JLabel Label_Roll;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField secTF;
    // End of variables declaration//GEN-END:variables
}
